export const translations = {
  id: {
    appTagline: "SME",
    btnAdd: "+ Tambah Transaksi",
    btnAddShort: "+ Tambah",
    btnLogout: "Keluar",
    tabSummary: "Ringkasan",
    tabCashflow: "Arus Kas",
    tabExpense: "Pengeluaran",
    tabTransaction: "Transaksi",
    pageTitle: "Ringkasan Bisnis",
    pageSubtitle: "Semua angka dalam Rupiah",
    kpiRevenue: "Total Pendapatan",
    kpiExpense: "Total Pengeluaran",
    kpiProfit: "Laba Bersih",
    kpiMargin: "Margin Laba",
    kpiSub: "dari transaksi",
    chartTitle: "Pendapatan vs Pengeluaran",
    chartSub: "Tren per bulan",
    pieTitle: "Rincian Pengeluaran",
    pieSub: "Per kategori",
    noExpense: "Belum ada pengeluaran",
    recentTitle: "Transaksi Terbaru",
    viewAll: "Lihat semua →",
    noTransaction: "Belum ada transaksi — klik \"+Tambah\" untuk mulai",
    cashflowTitle: "Arus Kas",
    cashflowSub: "Pendapatan vs pengeluaran per bulan",
    noData: "Belum ada data transaksi",
    income: "Pendapatan",
    expense: "Pengeluaran",
    profit: "Laba",
    expenseTitle: "Analisis Pengeluaran",
    expenseSub: "Kemana uang kamu pergi",
    byCategory: "Per Kategori",
    breakdown: "Rincian",
    noExpenseData: "Belum ada data pengeluaran",
    transactionTitle: "Transaksi",
    searchPlaceholder: "Cari transaksi...",
    filterAll: "semua",
    filterIncome: "pemasukan",
    filterExpense: "pengeluaran",
    noResult: "Tidak ada transaksi",
    dataCount: "data",
    modalTitle: "Tambah Transaksi",
    typeIncome: "pemasukan",
    typeExpense: "pengeluaran",
    descPlaceholder: "Keterangan",
    amountPlaceholder: "Jumlah (Rp)",
    btnSubmit: "Tambah Transaksi",
    categories: ["Pendapatan", "Gaji", "Operasional", "Marketing", "Teknologi", "Aset", "Lainnya"],
    authTitle: "Masuk ke akun",
    authTitleRegister: "Daftar akun baru",
    authTagline: "Dashboard keuangan untuk bisnis kamu",
    btnGoogle: "Masuk dengan Google",
    orEmail: "atau dengan email",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    btnLogin: "Masuk",
    btnRegister: "Daftar",
    loading: "Loading...",
    noAccount: "Belum punya akun? ",
    haveAccount: "Sudah punya akun? ",
    registerLink: "Daftar sekarang",
    loginLink: "Masuk",
    checkEmail: "Cek email kamu untuk konfirmasi pendaftaran!",
    loadingData: "Memuat data...",
    loadingApp: "Memuat...",
  },
  en: {
    appTagline: "SME",
    btnAdd: "+ Add Transaction",
    btnAddShort: "+ Add",
    btnLogout: "Sign Out",
    tabSummary: "Overview",
    tabCashflow: "Cash Flow",
    tabExpense: "Expenses",
    tabTransaction: "Transactions",
    pageTitle: "Business Overview",
    pageSubtitle: "All figures in Rupiah",
    kpiRevenue: "Total Revenue",
    kpiExpense: "Total Expenses",
    kpiProfit: "Net Profit",
    kpiMargin: "Profit Margin",
    kpiSub: "from transactions",
    chartTitle: "Revenue vs Expenses",
    chartSub: "Monthly trend",
    pieTitle: "Expense Breakdown",
    pieSub: "By category",
    noExpense: "No expenses yet",
    recentTitle: "Recent Transactions",
    viewAll: "View all →",
    noTransaction: "No transactions yet — click \"+Add\" to start",
    cashflowTitle: "Cash Flow",
    cashflowSub: "Revenue vs expenses per month",
    noData: "No transaction data yet",
    income: "Revenue",
    expense: "Expenses",
    profit: "Profit",
    expenseTitle: "Expense Analysis",
    expenseSub: "Where your money is going",
    byCategory: "By Category",
    breakdown: "Breakdown",
    noExpenseData: "No expense data yet",
    transactionTitle: "Transactions",
    searchPlaceholder: "Search transactions...",
    filterAll: "all",
    filterIncome: "income",
    filterExpense: "expense",
    noResult: "No transactions found",
    dataCount: "records",
    modalTitle: "Add Transaction",
    typeIncome: "income",
    typeExpense: "expense",
    descPlaceholder: "Description",
    amountPlaceholder: "Amount (Rp)",
    btnSubmit: "Add Transaction",
    categories: ["Revenue", "Salary", "Operations", "Marketing", "Technology", "Assets", "Other"],
    authTitle: "Sign in to your account",
    authTitleRegister: "Create new account",
    authTagline: "Financial dashboard for your business",
    btnGoogle: "Sign in with Google",
    orEmail: "or with email",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    btnLogin: "Sign In",
    btnRegister: "Register",
    loading: "Loading...",
    noAccount: "Don't have an account? ",
    haveAccount: "Already have an account? ",
    registerLink: "Register now",
    loginLink: "Sign in",
    checkEmail: "Check your email to confirm registration!",
    loadingData: "Loading data...",
    loadingApp: "Loading...",
  }
};

export function detectLang() {
  const saved = localStorage.getItem('lang');
  if (saved) return saved;
  const browser = navigator.language || navigator.userLanguage || 'en';
  return browser.startsWith('id') ? 'id' : 'en';
}

export function saveLang(lang) {
  localStorage.setItem('lang', lang);
}